# Default patterns for files that typically shouldn't be included in LLM prompts
DEFAULT_IGNORE_PATTERNS = [
    # Version Control
    ".git",
    ".gitignore",
    ".gitattributes",
    ".hg",
    ".hgignore",
    ".svn",
    # Python
    ".python-version",
    "pyproject.toml",
    "poetry.lock",
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "uv.lock",
    "ruff.toml",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    ".pytest_cache",
    ".coverage",
    ".tox",
    ".venv",
    "venv",
    # Node.js
    "package.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "node_modules",
    ".npmrc",
    ".yarnrc",
    # IDE and Editor
    ".vscode",
    ".idea",
    ".vs",
    "*.swp",
    "*.swo",
    ".DS_Store",
    # Build and Distribution
    "dist",
    "build",
    "*.egg-info",
    "*.whl",
    # Environment and Configuration
    ".env",
    ".env.*",
    "*.cfg",
    ".editorconfig",
    # Documentation
    "LICENSE",
    "LICENSE.*",
    "COPYING",
    "AUTHORS",
]

EXTENSIONS_MAP = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".jsx": "jsx",
    ".tsx": "tsx",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".sql": "sql",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".cpp": "cpp",
    ".c": "c",
    ".rb": "ruby",
    ".php": "php",
    ".md": "markdown",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".xml": "xml",
    ".toml": "toml",
}
